[Component]
    Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.checkoutservice"
    Version = "1.2.2"
    ChartName = "chart/checkoutservice"
    DockerRepo = "quay.io/hipsterstore/checkoutservice"
    GitUrl = "https://github.com/ortelius/store-checkoutservice"
    HelmChart = "GLOBAL.HelmChart"
    Applications = [
        "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"
    ]