[Component]
    Components = [
        { Name = "GLOBAL.SF Tech.Online Store Company.Purchase Processing.Checkout Service.checkoutservice", Application = "GLOBAL.SF Tech.Online Store Company.Hipster Store.Dev.Hipster Store;Labor Day Sale;1_2_10_2"}
     ]    
    Version = "1.2.2"
    ChartName = "chart/checkoutservice"
    DockerRepo = "quay.io/hipsterstore/checkoutservice"
    GitUrl = "https://github.com/ortelius/store-checkoutservice"
    CustomAction = "GLOBAL.HelmChart"